mode: ${MODE:hazelcast}

zeebe:
  client:
    broker.gatewayAddress: ${ZEEBE_URL:127.0.0.1:26500}
    security.plaintext: true

    worker:
      hazelcast:
        connection: ${HAZELCAST_URL:localhost:5701}
        connectionTimeout: PT30S
elastic:
  url: ${ZEEBE_ELASTIC_URL}
  user: ${ZEEBE_ELASTIC_USER}
  password: ${ZEEBE_ELASTIC_PASSWORD}
  index: ${ZEEBE_ELASTIC_INDEX}

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:""}
    driverClassName: ${DB_DRIVER:org.h2.Driver}

  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082
  servlet:
    context-path: /
  allowedOriginsUrls: ""

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: zeebe-simple-monitor

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
