zeebe:
  client:
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S

retention:
  enabled: ${RETENTION_ENABLED:false}
  interval: ${RETENTION_INTERVAL:PT24H}
  age: ${RETENTION_AGE:PT168H}

spring:
  datasource:
    url: jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10
  profiles:
    active: ${PROFILE:hazelcast}

  flyway:
    baseline-version: 1
    enabled: true
    locations: "classpath:db/migration/{vendor}"
    baseline-on-migrate: true


server:
  port: 8082
  servlet:
    context-path: /
  allowedOriginsUrls: ""

logging:
  level:
    root: ERROR
    io.zeebe: INFO

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      diskspace.enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, refresh
  prometheus.metrics.export.enabled: true

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
---
spring:
  config:
    activate:
      on-profile: kafka
kafkaBootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafkaSchemaRegistryUrl: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
kafka:
  streams:
    maxMessageSizeBytes: ${KAFKA_MAX_MESSAGE_SIZE_BYTES:5242880}
    numOfThreads: ${NUMBER_OF_STREAMS_THREAD:4}
