#DEBUG: true
zeebe:

  client:
    broker.contactPoint: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        enabled: true
        connection: localhost:5701
        connectionTimeout: PT30S
      kafka:
        enabled: false
        consumerProperties: |
          bootstrap.servers=kafka:9093
          group.id=zeebe-simple-monitor
          auto.offset.reset=earliest

spring:

  datasource:
    url: jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN

