version: "3"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.2.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_HAZELCAST_CLUSTER_NAME=dev
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    networks:
      - zeebe_network

  simple-monitor-in-memory:
    container_name: zeebe-simple-monitor-in-memory
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - zeebe.client.worker.hazelcast.clusterName=dev
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
    profiles:
      - in-memory

  simple-monitor-postgres:
    container_name: zeebe-simple-monitor-postgres
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - zeebe.client.worker.hazelcast.clusterName=dev
      - spring.datasource.url=jdbc:postgresql://postgres-zeebe-simple-monitor:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - postgres-zeebe-simple-monitor
    networks:
      - zeebe_network
    profiles:
      - postgres

  postgres-zeebe-simple-monitor:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - postgres-zeebe-simple-monitor-data:/var/lib/postgresql/data
    networks:
      - zeebe_network
    profiles:
      - postgres

  simple-monitor-mysql:
    container_name: zeebe-simple-monitor-mysql
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - zeebe.client.worker.hazelcast.clusterName=dev
      - spring.datasource.url=jdbc:mysql://mysql-zeebe-simple-monitor:3306/simple_monitor?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - mysql-zeebe-simple-monitor
    networks:
      - zeebe_network
    profiles:
      - mysql

  mysql-zeebe-simple-monitor:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zeebe
    volumes:
      - mysql-zeebe-simple-monitor-data:/var/lib/mysql
    networks:
      - zeebe_network
    profiles:
      - mysql

volumes:
  postgres-zeebe-simple-monitor-data:
    driver: local
  mysql-zeebe-simple-monitor-data:
    driver: local
